### PR TITLE
New itertool: ipartition

### PR DESCRIPTION
**Pull request by Rosuav**
Not sure if this would be of interest to you, but it's something I knocked together in response to a python-list question and Tim Chase said it might be of use. It looks like you're using the MIT license? I'm okay with that, if it is.

### CODE REVIEW

**Comment by erikrose** [comment]
I like the idea. I'd like to…

1. Code it with less repetition and
2. See if it can be readily expanded to an arbitrary number of partitions, as I was thinking of adding a bucket() function that did that anyway. (You'd pass in a `key` function that returned any number of bucket identifiers, and `partition` (or `bucket`, which would be a better name for the larger version) might become indexable so you could get at all the buckets: `buckets = bucket(bool, iterable); print next(buckets[true])`.)

Crazy?

**Comment by bbayles** [comment]
I like the `dict` in @cvrebert's version, but was planning on playing with it to see if we can avoid pulling the iterable into memory.

**Comment by bbayles** [comment]
I think I've got something that could work in 054f4c79871ec6441644e41d2697941116b8cdad; I'll play some more and make a PR with any changes.

**Comment by bbayles** [comment]
I'll close this issue in favor of #66, which has tests and such.

**Pull request closed without merging**
