### PR TITLE
Simply intersperse()

### PR DESCRIPTION
**Pull request by bbayles**
This PR changes the implementation of `intersperse()` to take out the Python loop and replace it with C itertools. My testing shows it to be 15%-20% faster on a 1000-item iterable.

---

The reason this implementation works is that interspersing is close to `zip`-ing.

If we create an infinite iterable interspersed element `e` with `repeat`, we get this when we `zip` it with the our iterable:
```python
>>> from itertools import repeat
...
... iterable = [0, 1, 2, 3]
... e = '?'
... filler = repeat(e)
... list(zip(filler, iter(iterable)))
[('?', 0), ('?', 1), ('?', 2), ('?', 3)]
```

If we `flatten` that, we get almost what we want - the only difference is an extra `e` at the beginning:
```python
>>> from itertools import chain
...
... list(chain.from_iterable([('?', 0), ('?', 1), ('?', 2), ('?', 3)]))
['?', 0, '?', 1, '?', 2, '?', 3]
```
We can chop that off with `islice`:
```python
>>> from itertools import islice
...
... list(islice(['?', 0, '?', 1, '?', 2, '?', 3], 1, None))
[0, '?', 1, '?', 2, '?', 3]
```

Which is what we want.

### CODE REVIEW

**Comment by pylang** [comment]
zipping an iterator advanced with `next()`.  Nice!

**Comment by bbayles** [comment]
Your comment inspired me to check if doing `next(...)` on the `flatten`-ed iterable is faster. It is indeed! Another 5%-10% boost.

**Comment by erikrose** [comment]
Not only a speed improvement but a conciseness one as well, especially in the tests. Lgtm!

**Comment by pylang** [comment]
Score!

**Pull request merged**
