### PR TITLE
Issue #100: Added feature sort_together with tests

### PR DESCRIPTION
**Pull request by clintval**

### CODE REVIEW

**Comment by bbayles** [comment]
Apologies for introducing the conflicts. If you fetch from this repository and do `git cherry-pick 6f9cd5f35129327de5e421da0f305a8beb921789` then you can get my fixes for them.

**Comment by clintval** [comment]
After fetching and entering `git cherry-pick 6f9cd5f35129327de5e421da0f305a8beb921789` I end up with a fatal error: `bad object` FYI. Thanks for your careful review! I agree with all your points (didn't even know about `NORMALIZE_WHITESPACE`!). Is there anything you need from me still? Are any of your comments still unfixed? Thanks!

**Comment by bbayles** [comment]
Hm, as far as I can see there are only the first two commits here, so still those changes are needed?

**Comment by bbayles** [comment]
I had a thought to add a usage note to the docstring; I'll push a different PR for that with your commits in it with that addition (plus fixes for the merge conflicts I caused).

**Pull request merged**
