### PR TITLE
Readme function overview table

### PR DESCRIPTION
**Pull request by MSeifert04**
xref #214 

It's probably not yet perfect but it contains all functions in the API Documentation.

Before I start on the ReadTheDocs RST documentation I wanted to wait for some feedback.

cc @pylang

### CODE REVIEW

**Comment by MSeifert04** [comment]
You can visit the branch in case you want to know how it would look like: https://github.com/MSeifert04/more-itertools/tree/table

**Comment by pylang** [comment]
@MSeifert04  That looks great!  Thank you.  It looks like it's as simple as copying the link in the table section.  I went through then links and they direct to correct tool.

**Comment by MSeifert04** [comment]
@pylang Thanks for checking the links! 👍 

I'm not sure about the position in the ReadMe, maybe they should be after the "api reference" mention. I also didn't check if it works with "code-formatting" the links. I may be able to check that tomorrow.

Since I didn't created that table by hand: Would it make sense to put the doc-scraping and rst-formatting code in the repo?

**Comment by bbayles** [comment]
This looks good - thanks!

Re: placement, I might play with it later, but I think that's a good place to put it to start.

Re: "code formatting," I don't think it's necessary, and might looks a little weird.

Re: generation code, perhaps you could post it here?

One nitpick, which might be a pain to do - I put the categories on the left side of [the docs](https://more-itertools.readthedocs.io/en/latest/api.html) in that order deliberately. I think I'd like to have the categories in that same order in the table?

**Comment by MSeifert04** [comment]
Okay, I removed the sorting.

The script is basically this (not particularly elegant and probably easy to break):

```
from collections import defaultdict
from astropy.io.ascii import RST

path_to_more_itertools = # insert your path to the more-itertools repo here

groups = defaultdict(list)
current_group = None
last_line = None
with open(path_to_more_itertools + 'docs/api.rst') as file:
    for line in file:
        if line.strip().startswith("===") and last_line is not None:
            current_group = last_line.strip()
        if line.strip().startswith(".. auto"):
            function = line.strip().split('::')[1].split('(')[0].strip()
            link = f'`{function} <https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.{function}>`_'
            groups[current_group].append(link)
        last_line = line
        
del groups["API Reference"]  # remove unnecessary API Reference group...
    
r = []
for group_name, functions in groups.items():
    if not functions:  # remove empty groups
        del groups[group_name]
        continue
    r.append((group_name, ', '.join(sorted(functions))))
    
from astropy.table import Table
print('\n'.join(RST().write(Table(rows=r))[2:]))  # convert to Table and throw away the first two header lines...
```

**Comment by bbayles** [comment]
I found [this](https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html), which seems to fit the bill.

I also changed around the table format to make it more easily hand-editable. See [here](https://raw.githubusercontent.com/erikrose/more-itertools/bbayles-tables/README.rst). What do you think of that?

**Comment by MSeifert04** [comment]
Yeah, I have known about the line-wrapping problem in RTD. I just haven't thought that you actually include the README in the docs.

I like the alternative design. 👍 Did you generate that based on a script or by hand? I know my script is fragile but at least (if it works) it can do all automatically without any manual intervention - so there might be a reason to actually do it by script - or not, if you don't expect it to be a problem.

It's still a bit annoying if one adds a function with a longer name but that's far less likely than adding another function to a group.

**Comment by bbayles** [comment]
The table was semi-scripted. My intention is to only update it at release time. I may regret this format if I introduce a new category, but we'll see how this works. Thanks for the contribution!

**Comment by pylang** [comment]
@bbayles I went through the links in the talbe again.  Looks like `last()` and `rlocate()` don't point to any tool.  I think it's bc the links point to the *stable* version of RTD instead of *latest* version.  That means, new tools won't have links until the next release.

**Pull request merged**
