### PR TITLE
clarify ilen

### PR DESCRIPTION
**Pull request by bmintz**
This uses the same technique, but should be easier to follow.
It is around the same speed as the old approach, in my testing.

### CODE REVIEW

**Comment by MSeifert04** [comment]
> It is around the same speed as the old approach, in my testing

Could you share your timings? Because it is significantly slower  in the cases i tested.

**Comment by MSeifert04** [comment]
Maybe I was a bit too fast. I made some more timings and wanted to share them:

```
%matplotlib notebook

from simple_benchmark import benchmark # from https://github.com/MSeifert04/simple_benchmark
from collections import deque

def ilen_deque(xs):
    d = deque(enumerate(xs, 1), maxlen=1)
    return d[0][0] if d else 0

def ilen_loop(xs):
    len = 0
    for len, _ in enumerate(xs, 1):
        pass
    return len

def ilen_deque_it(xs):
    return ilen_deque((i for i in xs))

def ilen_loop_it(xs):
    return ilen_loop((i for i in xs))

b = benchmark([ilen_deque, ilen_loop, ilen_deque_it, ilen_loop_it],
              {2**i: [0]*(2**i) for i in range(1, 20)},
              'length')
b.plot()
```

png image 785 x 528 pixels

```
b.plot(relative_to=ilen_loop)
```
png image 800 x 429 pixels

Based on Python 3.7 (I haven't done any timings on other Python versions - but probably should be done)

**Comment by bmintz** [comment]
Am I reading the graphs correctly? Seems that ilen_loop is fastest.

**Comment by bbayles** [comment]
Nice work. I'll merge this if the items `flake8` flags in the CI runs are fixed?

**Comment by bbayles** [comment]
Oh, and perhaps you could change the loop variable to something other than `len`? I'm allergic to shadowing built-ins.

**Comment by bmintz** [comment]
lol i don't highlight builtins intentionally because `id` is such a great name. 
but ok, i will change it to length.
Also, I have a faster approach.

**Comment by bmintz** [comment]
Please make sure this is indeed faster than the enumerate approach.

**Comment by bbayles** [comment]
FYI, the CI tests are still failing on this:

```
./more_itertools/more.py:906:13: W504 line break after binary operator
./more_itertools/more.py:907:13: W504 line break after binary operator
```

**Comment by bmintz** [comment]
It's not my code though?

**Comment by bbayles** [comment]
Oh, perhaps flake8 updated? Thanks for pointing that out.

**Comment by MSeifert04** [comment]
Just FYI if I compare it to [`iteration_utilities.count_items`](https://iteration-utilities.readthedocs.io/en/latest/generated/count_items.html#iteration_utilities.count_items) (I hope you forgive me the advertising):

png image 573 x 429 pixels

**Comment by MSeifert04** [comment]
But again: this should also be tested on other computers (and probably on other Python versions).

**Comment by MSeifert04** [comment]
You could also try `returns sum(1 for _ in xs)`. Maybe that is faster.

**Comment by bmintz** [comment]
@MSeifert04 can you try it with your benchmarking tool?
I don't think it'll be faster though, since it has to step into and out of a generator.

**Comment by MSeifert04** [comment]
> @MSeifert04 can you try it with your benchmarking tool?
>I don't think it'll be faster though, since it has to step into and out of a generator.
Yes, that's what I thought too. And I checked it, it's slower (roughly equal to the `+= 1` approach).

**Comment by bbayles** [comment]
Many thanks for the analysis here.

**Comment by achampion** [comment]
So using the benchmark reference above using `zip()` and `itertools.count()` looks like:

``` python
def ilen_zip(iterable):
    counter = it.count()
    deque(zip(iterable, counter), maxlen=0)
    return next(counter)
```

image

**Comment by MSeifert04** [comment]
What Python version?

Btw I lile the style of the plot which one is this? Ggplot?

**Comment by achampion** [comment]
Python 3.7.1 but it was also faster in Py3.6 (see https://github.com/erikrose/more-itertools/issues/230).  
The style is `ggplot`:

    from matplotlib import pyplot as plt
    plt.style.use('ggplot')

**Comment by MSeifert04** [comment]
Ah thank you.

I don't know what's different on my installation but probably the performance of `ilen` should be tested on a broader set of computers and python versions.

**Pull request merged**
